# -*- coding: utf-8 -*-
from setuptools import setup

packages = ['aiohttpretty']

package_data = {'': ['*']}

install_requires = [
    'aiohttp>=3.8.1,<4.0.0',
    'furl>=2.1.3,<3.0.0',
    'multidict>=6.0.2,<7.0.0',
    'yarl>=1.7.2,<2.0.0',
]

entry_points = {'pytest11': ['aiohttpretty = aiohttpretty.plugin']}

classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3',
]

setup_kwargs = {
    'name': 'aiohttpretty',
    'version': '0.1.0',
    'description': 'AioHTTPretty',
    'long_description': None,
    'author': 'Center for Open Science',
    'author_email': 'contact@cos.i',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
    'classifiers': classifiers,
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
